export const appName = 'Nepal Geo Explorer';

export const gameModes = {
    province: 'Province mode',
    district: 'District mode',
    provinceFixed: 'Province fixed mode',
    districtFixed: 'District fixed mode',
};

export const ONE_SECOND = 1000;
export const ONE_MINUTE = 60 * ONE_SECOND;

export const ROUND_DURATION = 5 * ONE_SECOND;
export const MAX_ATTEMPTS = 3;

export const TOTAL_PROVINCES = 7;
export const TOTAL_DISTRICTS = 77;
export const PROVINCE_MAX_ROUNDS = 5;
export const DISTRICTS_MAX_ROUNDS = 10;


export const provinces = [
    {
        id: 4,
        code: 'gandaki',
        title: 'Gandaki',
        title_ne: 'गण्डकी',
    },
    {
        id: 3,
        code: 'p3',
        title: 'Bagmati',
        title_ne: 'बाग्मती',
    },
    {
        id: 7,
        code: 'sudurpaschim',
        title: 'Sudurpashchim',
        title_ne: 'सुदुरपश्चिम',
    },
    {
        id: 1,
        code: 'p1',
        title: 'Province 1',
        title_ne: 'प्रदेश नं .१',
    },
    {
        id: 5,
        code: 'p5',
        title: 'Province 5',
        title_ne: 'प्रदेश नं .५',
    },
    {
        id: 2,
        code: 'p2',
        title: 'Province 2',
        title_ne: 'प्रदेश नं .२',
    },
    {
        id: 6,
        code: 'karnali',
        title: 'Karnali',
        title_ne: 'कर्णाली',
    },
];

export const districts = [
    {
        id: 5,
        code: 'morang',
        title: 'Morang',
        title_ne: 'मोरङ्ग',
        province: 1,
    },
    {
        id: 7,
        code: 'dhankuta',
        title: 'Dhankuta',
        title_ne: 'धनकुटा',
        province: 1,
    },
    {
        id: 8,
        code: 'tehrathum',
        title: 'Terhathum',
        title_ne: 'तेह्रथुम',
        province: 1,
    },
    {
        id: 10,
        code: 'sankhuwasabha',
        title: 'Sankhuwasabha',
        title_ne: 'संखुवासभा',
        province: 1,
    },
    {
        id: 11,
        code: 'solukhumbu',
        title: 'Solukhumbu',
        title_ne: 'सोलुखुम्वु',
        province: 1,
    },
    {
        id: 12,
        code: 'khotang',
        title: 'Khotang',
        title_ne: 'खोटाङ्ग',
        province: 1,
    },
    {
        id: 14,
        code: 'udayapur',
        title: 'Udayapur',
        title_ne: 'उदयपुर',
        province: 1,
    },
    {
        id: 15,
        code: 'siraha',
        title: 'Siraha',
        title_ne: 'सिराहा',
        province: 2,
    },
    {
        id: 18,
        code: 'mahottari',
        title: 'Mahottari',
        title_ne: 'महोत्तरी',
        province: 2,
    },
    {
        id: 19,
        code: 'sarlahi',
        title: 'Sarlahi',
        title_ne: 'सर्लाही',
        province: 2,
    },
    {
        id: 22,
        code: 'dolakha',
        title: 'Dolakha',
        title_ne: 'दोलखा',
        province: 3,
    },
    {
        id: 23,
        code: 'rasuwa',
        title: 'Rasuwa',
        title_ne: 'रसुवा',
        province: 3,
    },
    {
        id: 26,
        code: 'dhading',
        title: 'Dhading',
        title_ne: 'धादिङ्ग',
        province: 3,
    },
    {
        id: 28,
        code: 'lalitpur',
        title: 'Lalitpur',
        title_ne: 'ललितपुर',
        province: 3,
    },
    {
        id: 29,
        code: 'bhaktapur',
        title: 'Bhaktapur',
        title_ne: 'भक्तपुर',
        province: 3,
    },
    {
        id: 32,
        code: 'rautahat',
        title: 'Rautahat',
        title_ne: 'रौतहट',
        province: 2,
    },
    {
        id: 33,
        code: 'bara',
        title: 'Bara',
        title_ne: 'वारा',
        province: 2,
    },
    {
        id: 61,
        code: 'kalikot',
        title: 'Kalikot',
        title_ne: 'कालिकोट',
        province: 6,
    },
    {
        id: 64,
        code: 'surkhet',
        title: 'Surkhet',
        title_ne: 'सुर्खेत',
        province: 6,
    },
    {
        id: 67,
        code: 'kailali',
        title: 'Kailali',
        title_ne: 'कैलाली',
        province: 7,
    },
    {
        id: 69,
        code: 'achham',
        title: 'Achham',
        title_ne: 'आछाम',
        province: 7,
    },
    {
        id: 75,
        code: 'kanchanpur',
        title: 'Kanchanpur',
        title_ne: 'कन्चनपुर',
        province: 7,
    },
    {
        id: 482,
        code: 'nawalparasiwest',
        title: 'Parasi',
        title_ne: 'नवलपरासी (बर्दघाट सुस्ता पश्चिम)',
        province: 5,
    },
    {
        id: 541,
        code: 'rukumeast',
        title: 'Rukum East',
        title_ne: 'रुकुम पूर्व',
        province: 5,
    },
    {
        id: 38,
        code: 'kapilvastu',
        title: 'Kapilbastu',
        title_ne: 'कपिलवस्तु',
        province: 5,
    },
    {
        id: 40,
        code: 'arghakhanchi',
        title: 'Arghakhanchi',
        title_ne: 'अर्घाखाची',
        province: 5,
    },
    {
        id: 41,
        code: 'gulmi',
        title: 'Gulmi',
        title_ne: 'गुल्मी',
        province: 5,
    },
    {
        id: 44,
        code: 'gorkha',
        title: 'Gorkha',
        title_ne: 'गोर्खा',
        province: 4,
    },
    {
        id: 46,
        code: 'kaski',
        title: 'Kaski',
        title_ne: 'कास्की',
        province: 4,
    },
    {
        id: 47,
        code: 'manang',
        title: 'Manang',
        title_ne: 'मनाङ्ग',
        province: 4,
    },
    {
        id: 50,
        code: 'baglung',
        title: 'Baglung',
        title_ne: 'वागलुङ्ग',
        province: 4,
    },
    {
        id: 51,
        code: 'parbat',
        title: 'Parbat',
        title_ne: 'पर्वत',
        province: 4,
    },
    {
        id: 57,
        code: 'dolpa',
        title: 'Dolpa',
        title_ne: 'डोल्पा',
        province: 6,
    },
    {
        id: 58,
        code: 'mugu',
        title: 'Mugu',
        title_ne: 'मुगु',
        province: 6,
    },
    {
        id: 1,
        code: 'taplejung',
        title: 'Taplejung',
        title_ne: 'ताप्लेजुङ',
        province: 1,
    },
    {
        id: 2,
        code: 'panchthar',
        title: 'Panchthar',
        title_ne: 'पाँचथर',
        province: 1,
    },
    {
        id: 3,
        code: 'ilam',
        title: 'Ilam',
        title_ne: 'इलाम',
        province: 1,
    },
    {
        id: 4,
        code: 'jhapa',
        title: 'Jhapa',
        title_ne: 'झापा',
        province: 1,
    },
    {
        id: 9,
        code: 'bhojpur',
        title: 'Bhojpur',
        title_ne: 'भोजपुर',
        province: 1,
    },
    {
        id: 13,
        code: 'okhaldhunga',
        title: 'Okhaldhunga',
        title_ne: 'ओखलढुङ्गा',
        province: 1,
    },
    {
        id: 16,
        code: 'saptari',
        title: 'Saptari',
        title_ne: 'सप्तरी',
        province: 2,
    },
    {
        id: 17,
        code: 'dhanusha',
        title: 'Dhanusa',
        title_ne: 'धनुषा',
        province: 2,
    },
    {
        id: 21,
        code: 'ramechhap',
        title: 'Ramechhap',
        title_ne: 'रामेछाप',
        province: 3,
    },
    {
        id: 24,
        code: 'sindhupalchowk',
        title: 'Sindhupalchok',
        title_ne: 'सिन्धुपाल्चोक',
        province: 3,
    },
    {
        id: 25,
        code: 'nuwakot',
        title: 'Nuwakot',
        title_ne: 'नुवाकोट',
        province: 3,
    },
    {
        id: 27,
        code: 'ktm',
        title: 'Kathmandu',
        title_ne: 'काठमाण्डौ',
        province: 3,
    },
    {
        id: 30,
        code: 'kavre',
        title: 'Kavrepalanchok',
        title_ne: 'काभ्रेपलाञ्चोक',
        province: 3,
    },
    {
        id: 31,
        code: 'makwanpur',
        title: 'Makwanpur',
        title_ne: 'मकवानपुर',
        province: 3,
    },
    {
        id: 34,
        code: 'parsa',
        title: 'Parsa',
        title_ne: 'पर्सा',
        province: 2,
    },
    {
        id: 59,
        code: 'humla',
        title: 'Humla',
        title_ne: 'हुम्ला',
        province: 6,
    },
    {
        id: 60,
        code: 'jumla',
        title: 'Jumla',
        title_ne: 'जुम्ला',
        province: 6,
    },
    {
        id: 62,
        code: 'jajarkot',
        title: 'Jajarkot',
        title_ne: 'जाजरकोट',
        province: 6,
    },
    {
        id: 63,
        code: 'dailekh',
        title: 'Dailekh',
        title_ne: 'दैलेख',
        province: 6,
    },
    {
        id: 65,
        code: 'bardiya',
        title: 'Bardiya',
        title_ne: 'वर्दिया',
        province: 5,
    },
    {
        id: 66,
        code: 'banke',
        title: 'Banke',
        title_ne: 'वाके',
        province: 5,
    },
    {
        id: 68,
        code: 'doti',
        title: 'Doti',
        title_ne: 'डोटी',
        province: 7,
    },
    {
        id: 70,
        code: 'bajura',
        title: 'Bajura',
        title_ne: 'वाजुरा',
        province: 7,
    },
    {
        id: 71,
        code: 'bajhang',
        title: 'Bajhang',
        title_ne: 'वझाङ्ग',
        province: 7,
    },
    {
        id: 73,
        code: 'baitadi',
        title: 'Baitadi',
        title_ne: 'वैतडी',
        province: 7,
    },
    {
        id: 542,
        code: 'rukumwest',
        title: 'Rukum West',
        title_ne: 'रुकुम पश्चिम',
        province: 6,
    },
    {
        id: 39,
        code: 'palpa',
        title: 'Palpa',
        title_ne: 'पाल्पा',
        province: 5,
    },
    {
        id: 42,
        code: 'syangja',
        title: 'Syangja',
        title_ne: 'स्याङ्गजा',
        province: 4,
    },
    {
        id: 43,
        code: 'tanahun',
        title: 'Tanahu',
        title_ne: 'तनहु',
        province: 4,
    },
    {
        id: 45,
        code: 'lamjung',
        title: 'Lamjung',
        title_ne: 'लमजुङ्ग',
        province: 4,
    },
    {
        id: 48,
        code: 'mustang',
        title: 'Mustang',
        title_ne: 'मुस्ताङ्ग',
        province: 4,
    },
    {
        id: 49,
        code: 'myagdi',
        title: 'Myagdi',
        title_ne: 'म्याग्दी',
        province: 4,
    },
    {
        id: 52,
        code: 'dang',
        title: 'Dang',
        title_ne: 'दाङ्ग',
        province: 5,
    },
    {
        id: 53,
        code: 'pyuthan',
        title: 'Pyuthan',
        title_ne: 'प्युठान',
        province: 5,
    },
    {
        id: 54,
        code: 'rolpa',
        title: 'Rolpa',
        title_ne: 'रोल्पा',
        province: 5,
    },
    {
        id: 55,
        code: 'salyan',
        title: 'Salyan',
        title_ne: 'सल्यान',
        province: 6,
    },
    {
        id: 6,
        code: 'sunsari',
        title: 'Sunsari',
        title_ne: 'सुनसरी',
        province: 1,
    },
    {
        id: 20,
        code: 'sindhuli',
        title: 'Sindhuli',
        title_ne: 'सिन्धुली',
        province: 3,
    },
    {
        id: 72,
        code: 'darchula',
        title: 'Darchula',
        title_ne: 'दार्चुला',
        province: 7,
    },
    {
        id: 74,
        code: 'dadeldhura',
        title: 'Dadeldhura',
        title_ne: 'डडेलधुरा',
        province: 7,
    },
    {
        id: 481,
        code: 'nawalparasieast',
        title: 'Nawalpur',
        title_ne: 'नवलपरासी (बर्दघाट सुस्ता पूर्व)',
        province: 4,
    },
    {
        id: 35,
        code: 'chitwan',
        title: 'Chitwan',
        title_ne: 'चितवन',
        province: 3,
    },
    {
        id: 37,
        code: 'rupandehi',
        title: 'Rupandehi',
        title_ne: 'रुपन्देही',
        province: 5,
    },
];
