import { listToMap } from '@togglecorp/fujs';

export const appName = 'Simana';

export const gameModes = {
    province: 'Province all',
    district: 'District all',
    provinceFixed: 'Province quick',
    districtFixed: 'District quick',
};

export const ONE_SECOND = 1000;
export const ONE_MINUTE = 60 * ONE_SECOND;

export const ROUND_DURATION = 15 * ONE_SECOND;
export const MAX_ATTEMPTS = 3;

export const TOTAL_PROVINCES = 7;
export const TOTAL_DISTRICTS = 77;
export const PROVINCE_MAX_ROUNDS = 5;
export const DISTRICTS_MAX_ROUNDS = 10;

export const SCORE_UNIT = 500;

export const DEFAULT_TICK_INTERVAL = 500;

export const positiveMessageList = [
    'Amazing!',
    'Awesome!',
    'Brilliant!',
    'Dazzling!',
    'Delightful!',
    'Fabulous!',
    'Fantastic!',
    'Good job!',
    'Great!',
    'Impressive!',
    'Perfect!',
    'Remarkable!',
    'Terrific!',
    'Wonderful!',
];


export const provinces = [
    {
        id: 4,
        code: 'gandaki',
        title: 'Gandaki',
        facts: [],
    },
    {
        id: 3,
        code: 'p3',
        title: 'Bagmati',
        facts: [],
    },
    {
        id: 7,
        code: 'sudurpaschim',
        title: 'Sudurpashchim',
        facts: [],
    },
    {
        id: 1,
        code: 'p1',
        title: 'Province 1',
        facts: [],
    },
    {
        id: 5,
        code: 'p5',
        title: 'Province 5',
        facts: [],
    },
    {
        id: 2,
        code: 'p2',
        title: 'Province 2',
        facts: [],
    },
    {
        id: 6,
        code: 'karnali',
        title: 'Karnali',
        facts: [],
    },
];

export const provinceIdByCode = listToMap(provinces, (d) => d.code, (d) => d.id);

export const rawDistricts = [
    {
        id: '69',
        code: 'achham',
        province: '7',
        title: 'Achham',
        fact_1: 'home to sanfebagar aiport (non functionally at the moment',
        fact_2: 'Budhiganga River Bridge',
        fact_3: 'rani tal and ramaroshan lake',
    },
    {
        id: '40',
        code: 'arghakhanchi',
        province: '5',
        title: 'Arghakhanchi',
        fact_1: 'Lies in Mahabharat mountain range',
        fact_2: 'Sano gau, Lamchi village is very popular',
        fact_3: 'supa deurali temple',
    },
    {
        id: '50',
        code: 'baglung',
        province: '4',
        title: 'Baglung',
        fact_1: 'Rich in herbal plants(rice, corn, millet)',
        fact_2: 'Also known as district of suspension bridges.',
    },
    {
        id: '73',
        code: 'baitadi',
        province: '7',
        title: 'Baitadi',
        fact_1: 'Cricket in very popular here. Home to may eminent national players',
        fact_2: '97% speak baitadeli',
        fact_3: 'Ishori Gangadhan Temple',
    },
    {
        id: '71',
        code: 'bajhang',
        province: '7',
        title: 'Bajhang',
        fact_1: 'Rich in Deuda Song and Deuda Dance',
        fact_2: 'Jalapa Devi Temple',
        fact_3: 'Famous for Milk and yogurt',
    },
    {
        id: '70',
        code: 'bajura',
        province: '7',
        title: 'Bajura',
        fact_1: 'Badimalika Temple',
        fact_2: 'Kaptad National Park',
        fact_3: 'Jethi Bahurani lekh and Karnali river are all part of Bajura.',
    },
    {
        id: '66',
        code: 'banke',
        province: '5',
        title: 'Banke',
        fact_1: 'Mostly Drained by Rapti river',
        fact_2: 'Bageshwari Temple',
        fact_3: 'Major cities of this part of nepal is located here',
    },
    {
        id: '33',
        code: 'bara',
        province: '2',
        title: 'Bara',
        fact_1: 'Gadhimai Temple',
        fact_2: 'Millions of people gather every 5 years for Gadhimai Mela.',
        fact_3: 'Bakaiya, Jamuniya, Pasaha, Dudhaura and Bangari are the main rivers of Bara.',
    },
    {
        id: '65',
        code: 'bardiya',
        province: '5',
        title: 'Bardiya',
        fact_1: 'Longest Concrete Bridge in Nepal',
        fact_2: 'Bardiya National Park, largest undisturbed wilderness in Nepal',
        fact_3: 'Home to most amount of Tigers in Nepal',
    },
    {
        id: '29',
        code: 'bhaktapur',
        province: '3',
        title: 'Bhaktapur',
        fact_1: 'Smallest District 119sq km',
        fact_2: 'City of Temples, Bhatkapur Durbar, Changu Narayan, Suryabinayak, etc',
        fact_3: 'Nagarkot, Pilot Baba',
        fact_4: 'Juju Dhau',
    },
    {
        id: '9',
        code: 'bhojpur',
        province: '1',
        title: 'Bhojpur',
        fact_1: 'Famous for metal work especially khukuri knives.',
        fact_2: 'Hatuwa Gadi lies here.',
        fact_3: 'Chhongkha Sakela celebration is popular here.',
    },
    {
        id: '35',
        code: 'chitwan',
        province: '3',
        title: 'Chitwan',
    },
    {
        id: '74',
        code: 'dadeldhura',
        province: '7',
        title: 'Dadeldhura',
        fact_1: 'desert-mountainous landscape',
        fact_2: 'Ugratara Tample,Ajaymerukot, Amarsingh fort',
        fact_3: 'known for folk songs and folk dance',
    },
    {
        id: '63',
        code: 'dailekh',
        province: '6',
        title: 'Dailekh',
        fact_1: 'major highway: Mid hill highway',
        fact_2: 'usually a stop for passerbys',
    },
    {
        id: '52',
        code: 'dang',
        province: '5',
        title: 'Dang',
        fact_1: 'Lamahi Bazar is a famous Transition point',
        fact_2: 'Ambikeshwari Temple',
        fact_3: 'Tharu community found since earliest times',
    },
    {
        id: '72',
        code: 'darchula',
        province: '7',
        title: 'Darchula',
        fact_1: 'gurans himal om parbat',
        fact_2: 'gateway to kailash mansorabar/kailash parbat',
        fact_3: 'askot musk deer sanctuary',
    },
    {
        id: '26',
        code: 'dhading',
        province: '3',
        title: 'Dhading',
        fact_1: 'Manakamana Temple',
        fact_2: 'Chandragiri Hills',
        fact_3: 'Lamo Jharana',
    },
    {
        id: '7',
        code: 'dhankuta',
        province: '1',
        title: 'Dhankuta',
        fact_1: 'Panoramic view of mountain with cool weather attracts tourists.',
        fact_2: 'Saptakoshi river and Dharan bazaar could be seen known as Charles point.',
    },
    {
        id: '17',
        code: 'dhanusha',
        province: '2',
        title: 'Dhanusa',
        fact_1: 'Janaki Temple Pilgrim site',
        fact_2: 'The only raiway sytem of Nepal',
        fact_3: 'kalo pothi film was shot here',
    },
    {
        id: '22',
        code: 'dolakha',
        province: '3',
        title: 'Dolakha',
    },
    {
        id: '57',
        code: 'dolpa',
        province: '6',
        title: 'Dolpa',
        fact_1: 'The main highlight of Dolpa trekking includes “Shey Phoksundo National Park / Lake deepest lake in nepal',
        fact_2: 'Snow leopard, musk deer',
        fact_3: 'Dolpo peak\\mt kanjirowa',
    },
    {
        id: '68',
        code: 'doti',
        province: '7',
        title: 'Doti',
        fact_1: '90% speak doteli',
        fact_2: 'shaileshwari temple silgadhi, malikasthan',
        fact_3: 'Doti used to be a kingdom stretched to india.',
    },
    {
        id: '44',
        code: 'gorkha',
        province: '4',
        title: 'Gorkha',
        fact_1: 'Location of Manakamana temple, gorakh kali etc.',
        fact_2: 'Manaslu, Ganesh Himal lies here.',
        fact_3: 'Also known as state of brave Gorkhalis.',
        fact_4: 'mount saipal and mount api',
    },
    {
        id: '41',
        code: 'gulmi',
        province: '5',
        title: 'Gulmi',
        fact_1: 'Tamghas is known for one of the best weathers and view in Nepal',
        fact_2: 'Renowned for being the place from where coffee was introduced. A lot of farms.',
        fact_3: 'Rich in Farming and Agriculture',
    },
    {
        id: '59',
        code: 'humla',
        province: '6',
        title: 'Humla',
        fact_1: 'There are more than 50 rivers in the district.',
        fact_2: 'potential to generate hydropower upto 10,300MW.',
        fact_3: 'aka hidden himalaya',
    },
    {
        id: '3',
        code: 'ilam',
        province: '1',
        title: 'Ilam',
        fact_1: 'Famous for tea production.',
        fact_2: 'Offers unique view of Mt.kanchenjunga',
        fact_3: 'Close to the famous Indian hill station i.e. Darjeeling.',
    },
    {
        id: '62',
        code: 'jajarkot',
        province: '6',
        title: 'Jajarkot',
        fact_1: 'dotted with temples',
        fact_2: 'most famous - shiva temple located in a cave',
        fact_3: 'tappa dance',
    },
    {
        id: '4',
        code: 'jhapa',
        province: '1',
        title: 'Jhapa',
        fact_1: 'Also known as Grain Grocery of Nepal.',
        fact_2: 'Chandragadi Fort is also located here.',
        fact_3: 'Kechanakalan and jamukhadi simsar i.e. wet land area lies here.',
    },
    {
        id: '60',
        code: 'jumla',
        province: '6',
        title: 'Jumla',
        fact_1: 'Sinja, the area above Jumla is a famous as the home of Nepal\'s main dialect which is the \'Khas Bhasa\'.',
        fact_2: 'Also known for its medicinal herbs or the jadibutis like Yarshagumba.',
        fact_3: 'mass production of apples',
    },
    {
        id: '67',
        code: 'kailali',
        province: '7',
        title: 'Kailali',
        fact_1: 'ghoda ghodi lake',
        fact_2: 'tikapur park',
        fact_3: 'dolphins can be seen here',
    },
    {
        id: '61',
        code: 'kalikot',
        province: '6',
        title: 'Kalikot',
        fact_1: 'Tila River is the main tributary that accommodates many species of fish including Asla.',
        fact_2: 'trekking route to Rara Lake with breathtaking sceneries throughout the way.',
        fact_3: 'steep hilly roads with almost everyone speaking nepali language',
    },
    {
        id: '75',
        code: 'kanchanpur',
        province: '7',
        title: 'Kanchanpur',
        fact_1: 'shuklaphanta national park',
        fact_2: 'tharu community',
        fact_3: 'dodhara chandani suspension bridge (longest suspension bridge in nepal)',
    },
    {
        id: '38',
        code: 'kapilvastu',
        province: '5',
        title: 'Kapilbastu',
        fact_1: 'Awadhi people are the major inhabintants',
        fact_2: 'Majority are Muslims',
        fact_3: 'World Marsh Region',
    },
    {
        id: '46',
        code: 'kaski',
        province: '4',
        title: 'Kaski',
        fact_1: 'Pokhara is its headquarter.',
        fact_2: 'It covers Annapurna Mountain Range.',
        fact_3: 'Fewa lake, begnas lake are the major attractions.',
    },
    {
        id: '27',
        code: 'ktm',
        province: '3',
        title: 'Kathmandu',
        fact_1: 'Capital',
        fact_2: 'Basantapur Durbar Square',
        fact_3: 'Pashupati, Swayambhu Temple',
    },
    {
        id: '30',
        code: 'kavre',
        province: '3',
        title: 'Kavrepalanchok',
        fact_1: 'Gupteshwor Cave/Palanchowk Bhagwati',
        fact_2: 'Photo Khichne Dhunga',
        fact_3: 'Simba Falls',
    },
    {
        id: '12',
        code: 'khotang',
        province: '1',
        title: 'Khotang',
        fact_1: 'Baraha pokhari lies here.',
        fact_2: 'Halesi Mahadev temple also lies here.',
        fact_3: 'Sunkoshi and dudhkoshi rivers are also present in this district.',
    },
    {
        id: '28',
        code: 'lalitpur',
        province: '3',
        title: 'Lalitpur',
        fact_1: 'Central Zoo',
        fact_2: 'Patan Museum/Durbar Square',
        fact_3: 'Krishna Mandir',
    },
    {
        id: '45',
        code: 'lamjung',
        province: '4',
        title: 'Lamjung',
        fact_1: 'Ghale gaun/Bhujung lies here, Famous for honey hunting',
        fact_2: 'Marshyangdi river flows here.',
        fact_3: 'Besisahar is situated here. This place is also famous for gurung home stays',
    },
    {
        id: '18',
        code: 'mahottari',
        province: '2',
        title: 'Mahottari',
        fact_1: 'Jaleshowar Mahadev temple',
        fact_2: '80% speak maithili',
    },
    {
        id: '31',
        code: 'makwanpur',
        province: '3',
        title: 'Makwanpur',
    },
    {
        id: '47',
        code: 'manang',
        province: '4',
        title: 'Manang',
        fact_1: 'Gets least amount of rainfall(desert of Nepal)',
        fact_2: 'Tilicho lake lies here.',
        fact_3: 'Manangis(Gurung and Ghale) are the dominant ethnic group.',
    },
    {
        id: '5',
        code: 'morang',
        province: '1',
        title: 'Morang',
        fact_1: 'Second largest city of Nepal lies here .',
        fact_2: 'Has the highest number of industries and factories.',
        fact_3: 'Raja Dani lake, Betana wet land area , jefale hill are the famous tourist destinations.',
    },
    {
        id: '58',
        code: 'mugu',
        province: '6',
        title: 'Mugu',
        fact_1: 'Rara Lake, Nepal\'s largest lake',
        fact_2: 'rato chamal',
        fact_3: 'kalo pothi film was shot here',
        fact_4: 'Benibazar as its centre.',
    },
    {
        id: '48',
        code: 'mustang',
        province: '4',
        title: 'Mustang',
        fact_1: 'Home to the Thakalis',
        fact_2: 'Lomanthang, Jomsom, Muktinath',
        fact_3: 'Also known as Cold Desert of Nepal',
    },
    {
        id: '49',
        code: 'myagdi',
        province: '4',
        title: 'Myagdi',
        fact_1: 'Mt. Dhaulagiri lies here.',
        fact_2: 'Annapurna range view.',
        fact_3: 'Famous for poonhill trekking.',
    },
    {
        id: '481',
        code: 'nawalparasieast',
        province: '4',
        title: 'Nawalpur',
        fact_1: 'Chaudhary Udhyog Gram (CUG), paper factory etc are the major industries.',
        fact_2: 'Maulakalika mandir, daaune devi mandir, etc are the major temples.',
        fact_3: 'Kawasoti is it’s headquarter.',
    },
    {
        id: '25',
        code: 'nuwakot',
        province: '3',
        title: 'Nuwakot',
        fact_1: 'Nuwakot Palace',
        fact_2: 'Shanti Dham',
        fact_3: 'Gurje Bhanjyang',
    },
    {
        id: '13',
        code: 'okhaldhunga',
        province: '1',
        title: 'Okhaldhunga',
        fact_1: 'Contains Ancient Forts such as Taluwagadhi.',
        fact_2: 'Birthplace of Nepalese Poet Siddhicharan Shrestha.',
        fact_3: 'Also Known as district of Martyrs.',
    },
    {
        id: '39',
        code: 'palpa',
        province: '5',
        title: 'Palpa',
        fact_1: 'Rani Mahal, Palpa Durbar',
        fact_2: 'Argeli Palace constructed by Juddha Shumsher',
        fact_3: 'Forts like Kalika fort, Nuwakot Fort, Bakumgadi Fort',
    },
    {
        id: '2',
        code: 'panchthar',
        province: '1',
        title: 'Panchthar',
        fact_1: 'Kiranti , Nepali are the major spoken languages.',
        fact_2: 'Kirantis (limbu,rais) are the major ethnic group of people here .',
        fact_3: 'Taldanda and singalila lies here.',
    },
    {
        id: '482',
        code: 'nawalparasiwest',
        province: '5',
        title: 'Parasi',
        fact_1: 'Separated in 2015 formerly known as Nawalparasi',
        fact_2: 'Ramgram Stupa',
    },
    {
        id: '51',
        code: 'parbat',
        province: '4',
        title: 'Parbat',
        fact_1: 'Gupteshwor cave, patheshwari temple are the major pilgrimage.',
        fact_2: 'Longest and highest suspension bridge of Nepal lies here.',
        fact_3: 'Rafting in Kaligandaki river, bungee, paragliding are major attraction.',
    },
    {
        id: '34',
        code: 'parsa',
        province: '2',
        title: 'Parsa',
        fact_1: 'Parsagadhi Temple',
        fact_2: 'Birjung clock tower ( ghanta ghar )',
    },
    {
        id: '53',
        code: 'pyuthan',
        province: '5',
        title: 'Pyuthan',
        fact_1: 'Jhimruk khola is the core',
        fact_2: 'Mallarani park',
        fact_3: 'One of the 24 small kingdoms in the chaubisi rajya',
    },
    {
        id: '21',
        code: 'ramechhap',
        province: '3',
        title: 'Ramechhap',
    },
    {
        id: '23',
        code: 'rasuwa',
        province: '3',
        title: 'Rasuwa',
        fact_1: 'Gosaikunda Lake with 108 different Lakes',
        fact_2: 'Langtang Himal',
        fact_3: 'Tamang Valley/Community',
    },
    {
        id: '32',
        code: 'rautahat',
        province: '2',
        title: 'Rautahat',
        fact_1: 'Rajdevi temple',
        fact_2: 'chandrapur view tower',
        fact_3: 'Gulab Narayan Jha, the first person to represent madhesis in politics',
    },
    {
        id: '54',
        code: 'rolpa',
        province: '5',
        title: 'Rolpa',
        fact_1: 'Bibang Dada',
        fact_2: 'Jyamire Daha Lakh',
        fact_3: 'One of the most remote places in Nepal',
        fact_4: 'has a beautiful pond called Rukmini Tal or locally Kamal Dhaha for its lotus flowers (kamal: lotus).',
    },
    {
        id: '541',
        code: 'rukumeast',
        province: '5',
        title: 'Rukum East',
        fact_1: 'Split in 2015 into 2 parts',
        fact_2: 'Sisne Himal view',
        fact_3: 'Thuli Daha Lake',
    },
    {
        id: '542',
        code: 'rukumwest',
        province: '6',
        title: 'Rukum West',
        fact_1: 'rich in yarsagumba.',
        fact_2: 'Mt. Sisne (Nepali: सिस्ने हिमाल),',
        fact_3: 'Shyarpu Tal (Lake)',
        fact_4: 'Salyani Khukuri:',
    },
    {
        id: '37',
        code: 'rupandehi',
        province: '5',
        title: 'Rupandehi',
        fact_1: 'Birthplace of Lord Buddha',
        fact_2: 'World Peace Pagoda, Maya Devi Temple .Lumbini Meseum',
    },
    {
        id: '55',
        code: 'salyan',
        province: '6',
        title: 'Salyan',
        fact_1: 'Kumakh hill, view of sisne himal, dhaulagiri, chakure himal',
        fact_2: 'Devi temple at Khairabang,, Chattreswori DeviTemple.',
        fact_3: 'babai river, kupinde taal',
    },
    {
        id: '10',
        code: 'sankhuwasabha',
        province: '1',
        title: 'Sankhuwasabha',
        fact_1: 'Deepest valley of the world lies here.',
        fact_2: 'Famous for Cardamom farming.',
        fact_3: 'Mt.Makalu also lies here.',
    },
    {
        id: '16',
        code: 'saptari',
        province: '2',
        title: 'Saptari',
        fact_1: 'Koshi Tappu Wildlife,',
        fact_2: 'Chinnamasta Bhagawati Temple,Shambhunath Temple,Sakhada Bhagwati, Kankalini Temple',
        fact_3: 'home to cricketer Mehboob Alam',
    },
    {
        id: '19',
        code: 'sarlahi',
        province: '2',
        title: 'Sarlahi',
        fact_1: 'lalbandhi',
        fact_2: 'largest sugar millls in nepal',
        fact_3: 'chure mountains range named sivalik hills',
    },
    {
        id: '20',
        code: 'sindhuli',
        province: '3',
        title: 'Sindhuli',
    },
    {
        id: '24',
        code: 'sindhupalchowk',
        province: '3',
        title: 'Sindhupalchok',
        fact_1: 'Tatopani , Near China-Nepal Border',
        fact_2: 'Sunkoshi Kafeshwar Mahadev Temple',
        fact_3: 'Bungy over Bhote Koshi river',
    },
    {
        id: '15',
        code: 'siraha',
        province: '2',
        title: 'Siraha',
        fact_1: 'home to yadav,thary,muslims',
        fact_2: 'Sagarmatha chaudhary eye hospital is very famous',
    },
    {
        id: '11',
        code: 'solukhumbu',
        province: '1',
        title: 'Solukhumbu',
        fact_1: 'Mount Everest',
        fact_2: 'Sherpa\'s Prime Place',
        fact_3: 'Trek and Tourist SIte',
    },
    {
        id: '6',
        code: 'sunsari',
        province: '1',
        title: 'Sunsari',
        fact_1: 'Buddha subba temple lies here.',
        fact_2: 'Saptakoshi river of Nepal is here.',
        fact_3: 'Bhedetar lies here which is one of the best hill station of Nepal.',
    },
    {
        id: '64',
        code: 'surkhet',
        province: '6',
        title: 'Surkhet',
        fact_1: 'Kakre Bihar—the “other Lumbini”',
        fact_2: 'Deuti Bajai—the wish-granting goddess',
        fact_3: 'The expansive, majestic Bulbule',
    },
    {
        id: '42',
        code: 'syangja',
        province: '4',
        title: 'Syangja',
        fact_1: 'Aalamdevi, panchase, satun chandi are the famous destinations.',
        fact_2: 'Kaligandaki \'A\' hydropower project, Nuwakot Durbar etc are located here.',
        fact_3: 'Millet, potato, buckwheat corn etc are major cash crops.',
    },
    {
        id: '43',
        code: 'tanahun',
        province: '4',
        title: 'Tanahu',
        fact_1: 'Bandipur is situated here.',
        fact_2: 'Byas cave, Chabdi barahi, panchu mandir etc are the major temples.',
    },
    {
        id: '1',
        code: 'taplejung',
        province: '1',
        title: 'Taplejung',
        fact_1: 'Pathibhara devi temple lies here.',
        fact_2: 'Mount Kanchenjunga lies here.',
        fact_3: 'Timbung pond and waterfall at Sawa are major tourist attractions.',
    },
    {
        id: '8',
        code: 'tehrathum',
        province: '1',
        title: 'Terhathum',
        fact_1: 'Offers closure view of Kanchenjunga and kumbakarna Mountains.',
        fact_2: 'Famous for 34 varieties of Rhododendron.',
        fact_3: 'Tinjure Dada which is popular for magnificent views of Sunrise and sunset lies here.',
    },
    {
        id: '14',
        code: 'udayapur',
        province: '1',
        title: 'Udayapur',
        fact_1: 'Triyuga river,koshi river lies here.',
        fact_2: 'Udaypur Gadhi lies here.',
        fact_3: 'Nepali,Tharu,Maithali are the major spoken languages .',
    },
];

export const districts = rawDistricts.map((d) => ({
    id: +d.id,
    code: d.code,
    title: d.title,
    facts: [
        d.fact_1,
        d.fact_2,
        d.fact_3,
        d.fact_4,
    ].filter((f) => f),
}));

export const districtIdByCode = listToMap(districts, (d) => d.code, (d) => d.id);
